language: node_js
node_js:
  - "stable"
cache:npm
branches:
  only:
  -  master
addons:
  ssh_known_hosts: git.wpengine.com
before_script:
  - npm ci
script:
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_0c3eeb54f1f2_key -iv $encrypted_0c3eeb54f1f2_iv -in beyond_parallel_travis.enc -out /tmp/beyond_parallel_travis -d
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
- provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master